#!/usr/bin/env bash
# Transfer a file from our client to a server using SCP

# Check if the number of arguments is less than 3
if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit
fi

# Check if the number of arguments is 4 or more
if [ $# -ge 4 ]; then
    # Use SCP with specified SSH key
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
else
    # Use SCP without specifying SSH key
    scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi

