#!/bin/bash

# Check if all 4 parameters are provided
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

# Display information about the transfer
echo "Transferring file: $file_path to $username@$server_ip:~/"

# Use scp to transfer the file with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username"@"$server_ip":~/

# Check if scp command was successful
if [ "$?" -eq 0 ]; then
    echo "File transfer successful!"
else
    echo "File transfer failed."
fi
