#!/usr/bin/env bash

# what’s keeping your Ubuntu container’s Nginx installation from listening on port 8 of all the server’s active IPv4 IPs?
# configures nginx to run and listen to port 80 of all the server’s active IPv4 IPs

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
