#!/usr/bin/env bash
# - Script that displays the content of the file `/etc/passwd`.
# - Scritp only displays the username, user id, and user home directory path.

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
