#!/usr/bin/env bash
# - Bash script that iterates from 1 to 10 and:
# - Displays "Bad luck" for the 4th iteration
# - Displays "Good luck" for the 8th iteration
# - Displays "Best School" for all other iterations

i=0
while [ $i -lt 10 ]
do
    if [ $i -eq 3 ]
    then
        echo "Bad luck"
    elif [ $i -eq 7 ]
    then 
        echo "Good luck"
    else
        echo "Best School"
    fi
    ((i++))
done
