#!/usr/bin/env bash
# - Bash script that iterates from 1 to 10 and:
# - Displays "Bad luck" for the 4th iteration
# - Displays "Good luck" for the 8th iteration
# - Displays "Best School" for all other iterations

counter=0
while [ $counter -lt 10 ]
do
    if [ $counter -eq 3 ]
    then
        echo "Bad luck"
    elif [ $counter -eq 7 ]
    then 
        echo "Good luck"
    else
        echo "Best School"
    fi
    ((counter++))
done
